### ISSUE TITLE
Default platform does not download ckeditor library anymore.

### ISSUE THREAD

**Issue by szeidler** [ramsalt/DrupalMakes#12]
Since https://github.com/ramsalt/DrupalMakes/commit/d3e4da2a92f8c03043dd345ea6f25a61ea15558a the ckeditor editor library is not downloaded anymore for the default platform. It will break the CKEditor functionality on new build platforms.

Every change needs to be double checked to not break the RamsaltMedia `drush make`.

**Comment by esolitos** [comment]
I believe that [dists/drupal7/platform-plain.build](https://github.com/ramsalt/DrupalMakes/blob/master/dists/drupal7/platform-plain.build) should include also [Ramsalt Base](https://bitbucket.org/ramsalt/ramsalt-base) otherwise there's no point having that repository separated from the RamsaltMedia.

I do agree that we should test our changes, we should also sort our dependency/inclusion madness which causes often this issues.
I will not have the required time to try to clean and test the changes any time soon, so i'll remove the assignment, in case this is not fully sorted before i come back i'll be glad to jump back in. :)
I'll follow the updates!

**Comment by szeidler** [comment]
Is https://bitbucket.org/ramsalt/ramsalt-base/src/87e0931fabe3184256d61ae153d9a88a244dec48/drupal-org.make?fileviewer=file-view-default the successor for https://github.com/ramsalt/DrupalMakes/blob/master/dists/base/base-d7-modules.make , because it seems to be really really similar. Meaning building a ramsaltmedia platform today, would download a huge amount of contrib modules twice.

Then the question is more about company policy. Should the default platform be buildable by the public or not ;)

**Comment by szeidler** [comment]
For me it seemed to be better, to sync the modules and libraries of both make files, to avoid version and patch mismatches. Atm, it could be the case, that some defined patches were applied only in RamsaltMedia platforms, or the other way around.

Including the RamsaltBase for the base modules, makes no sense, because the RamsaltBase module list is much bigger and more focussed on RamsaltMedia needs. Furthermore it also has the features folder, which should be only used for RamsaltMedia installations.

**Comment by esolitos** [comment]
Ramsalt *Base* should actually _not_ be related to Ramsalt *Media*, that is the whole point of the separation.
So it's "wrong"(ish) considering it R.Media focused, in RM there's another makefile just for that.

IMHO the correct solution should be having all the makefiles in this repository, with no "external ones", or define a strict policy, written somewhere that once can read and use as directive so that we know what goes where, altought it's not an easy thing to write.

As side note we discussed with @mnlund a few times if we should simply drop the "simple" platform in favor of "unifying" the platforms, we never reached a decision 'tho.

**Comment by szeidler** [comment]
Yes, it should not. But it has for example also a lot of features, like ramsalt_article, that are only used in the RamsaltMedia world. I know, it could be used also for other sites.

I totally agree with you. I would suggest for a merge of the platforms with no external ones. Ideally only here at github. Only additional features can be kept in additional repos.

I'm also open for a complete merge between both platform types, because there are often scenarios, where we use contrib modules from RM platforms in non-RM projects. But yeah, it needs some discussion rounds - and even more important: decisions!

**Comment by esolitos** [comment]
If you discuss such things now that I'm in paternity leave my vote is for merging the paltforms, this will lead to a stronger and more stable module handling overall.

**Comment by szeidler** [comment]
I'm not sure if we will be manage to get a decision here during your paternity leave. But I totally agree with you here: It happens so often to me, that I use ramsaltmedia contrib modules more often in default platform projects, than on ramsaltmedia projects :)

There is not much benefit in separating the platforms and as long we're not introducing every once-used contrib module into the platform, the overhead is not so big.
